# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    app.last_route_listener:
        class: AppBundle\EventListener\LastRouteListener
        tags:
            - { name: kernel.event_subscriber }
    app.song_voter:
        class: AppBundle\Security\SongVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false
    app.song_bundle_voter:
        class: AppBundle\Security\SongBundleVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
