language:
    locales:    { en: "/lang/{_locale}", nl: "/taal/{_locale}" }
    defaults:   { _controller: AppBundle:Default:locale }
    requirements:
        _locale: en|nl
login:
    locales:    { en: "/login/{view}", nl: "/inloggen/{view}" }
    defaults:   { _controller: AppBundle:Security:login, view: true }
logout:
    locales:    { en: "/logout", nl: "/uitloggen" }
security_password_recovery:
    locales:    { en: "/recover_password", nl: "wachtwoord_vergeten" }
    defaults:   { _controller: AppBundle:Security:recoverPassword }
security_change_password:
    locales:    { en: "/recover_password/{recoverId}", nl: "/wachtwoord_vergeten/{recoverId}" }
    defaults:   { _controller: AppBundle:Security:changePassword }
users_index:
    locales:    { en: "/users", nl: "/gebruikers" }
    defaults:   { _controller: AppBundle:Users:index }
users_register:
    locales:    { en: "/register", nl: "registeren" }
    defaults:   { _controller: AppBundle:Users:register }
users_create:
    locales:    { en: "/users/create", nl: "/gebruikers/nieuw" }
    defaults:   { _controller: AppBundle:Users:create }
users_edit:
    locales:    { en: "/users/edit/{id}", nl: "/gebruikers/wijzigen/{id}" }
    defaults:   { _controller: AppBundle:Users:edit }
song_bundles_index:
    locales:    { en: "/songs/bundles", nl: "/liederen/bundels" }
    defaults:   { _controller: AppBundle:SongBundles:index }
song_bundles_create:
    locales:    { en: "/songs/bundles/create", nl: "/liederen/bundels/nieuw" }
    defaults:   { _controller: AppBundle:SongBundles:create }
song_bundles_edit:
    locales:    { en: "/songs/bundles/edit/{id}", nl: "/liederen/bundels/wijzigen/{id}" }
    defaults:   { _controller: AppBundle:SongBundles:edit }
songs_index:
    locales:    { en: "/songs", nl: "/liederen" }
    defaults:   { _controller: AppBundle:Songs:index }
songs_create:
    locales:    { en: "/songs/create", nl: "/liederen/nieuw" }
    defaults:   { _controller: AppBundle:Songs:create }
songs_edit:
    locales:    { en: "/songs/edit/{id}", nl: "/liederen/wijzigen/{id}" }
    defaults:   { _controller: AppBundle:Songs:edit }
songs_view:
    locales:    { en: "/songs/{id}", nl: "/liederen/{id}" }
    defaults:   { _controller: AppBundle:Songs:view }
